
language: generic
sudo: false

matrix:
    include:

        # test installing bottleneck tarball before installing numpy;
        # start this test first because it takes the longest
        - os: linux
          env: TEST_DEPS="numpy nose"
               PYTHON_VERSION="2.7"
               PYTHON_ARCH="64"
               TEST_RUN="sdist"

         # flake8
        - os: linux
          env: TEST_DEPS="flake8"
               PYTHON_VERSION="2.7"
               PYTHON_ARCH="64"
               TEST_RUN="style"

        # python 3.5
        - os: linux
          env: TEST_DEPS="nose"
               PIP_DEPS="numpy>=1.16"
               PYTHON_VERSION="3.5"
               PYTHON_ARCH="64"
               TEST_RUN="sdist"

         # python 3.6
        - os: linux
          env: TEST_DEPS="numpy nose"
               PYTHON_VERSION="3.6"
               PYTHON_ARCH="64"

        # python 2.7
        - os: osx
          env: TEST_DEPS="numpy nose"
               PYTHON_VERSION="2.7"
               PYTHON_ARCH="64"
               TEST_RUN="sdist"

        # python 3.5
        - os: osx
          env: TEST_DEPS="nose"
               PIP_DEPS="numpy>=1.16"
               PYTHON_VERSION="3.5"
               PYTHON_ARCH="64"

        # python 3.6
        - os: osx
          env: TEST_DEPS="numpy nose"
               PYTHON_VERSION="3.6"
               PYTHON_ARCH="64"

before_install:
    - uname -a
    - source "tools/travis/conda_setup.sh"

install:
    - source "tools/travis/conda_install.sh"

script:
    - source "tools/travis/bn_setup.sh"

notifications:
    email:
        on_success: never
        on_failure: always
