language: generic
sudo: false
matrix:
    include:
        - os: linux
          env: TEST_DEPS="flake8" PYTHON_VERSION="2.7" PYTHON_ARCH="64" TEST_RUN="style"
        - os: linux
          env: TEST_DEPS="numpy==1.11.0 nose" PYTHON_VERSION="2.7" PYTHON_ARCH="64"
        - os: linux
          env: TEST_DEPS="nose" PYTHON_VERSION="2.7" PYTHON_ARCH="64" TEST_RUN="sdist"
        - os: linux
          env: TEST_DEPS="numpy==1.11.0 nose" PYTHON_VERSION="3.4" PYTHON_ARCH="64" TEST_RUN="sdist"
        - os: linux
          env: TEST_DEPS="numpy==1.11.0 nose" PYTHON_VERSION="3.5" PYTHON_ARCH="64"
        - os: osx
          env: TEST_DEPS="numpy==1.11.0 nose" PYTHON_VERSION="2.7" PYTHON_ARCH="64" TEST_RUN="sdist"
        - os: osx
          env: TEST_DEPS="numpy==1.11.0 nose" PYTHON_VERSION="3.4" PYTHON_ARCH="64"
        - os: osx
          env: TEST_DEPS="numpy==1.11.0 nose" PYTHON_VERSION="3.5" PYTHON_ARCH="64"

before_install:
    - uname -a
    - source "tools/travis/conda_setup.sh"

install:
    - source "tools/travis/conda_install.sh"

script:
    - source "tools/travis/bn_setup.sh"

notifications:
    email:
        on_success: never
        on_failure: always
