shallow_clone: true # download the zip instead of the whole history

environment:

    global:
        DEPS: "numpy=1.10 nose"
        CONDA_VENV: "testy"
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\windows_sdk.cmd"

    matrix:
        - PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "32"
          platform: x86
          CONDA_HOME: "C:\\Miniconda"

        - PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "64"
          platform: x64
          CONDA_HOME: "C:\\Miniconda"

        - PYTHON_VERSION: "3.4"
          PYTHON_ARCH: "32"
          platform: x86
          CONDA_HOME: "C:\\Miniconda3"

        - PYTHON_VERSION: "3.4"
          PYTHON_ARCH: "64"
          platform: x64
          CONDA_HOME: "C:\\Miniconda3"

        - PYTHON_VERSION: "3.5"
          PYTHON_ARCH: "32"
          platform: x86
          CONDA_HOME: "C:\\Miniconda3"

        - PYTHON_VERSION: "3.5"
          PYTHON_ARCH: "64"
          platform: x64
          CONDA_HOME: "C:\\Miniconda3"

install:
    - "SET PATH=%CONDA_HOME%;%CONDA_HOME%\\Scripts;%PATH%"
    # configures the Miniconda environment (Py2/Py3, 32/64 bit)
    - "python -u tools\\appveyor\\conda_setup.py"

build: false

test_script:
    - "activate %CONDA_VENV%"
    - "%CMD_IN_ENV% pip install --verbose ."
    - "python tools\\test-installed-bottleneck.py"
